# Generated by Django 3.2.11 on 2022-01-23 13:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=users.models.upload_path),
        ),
    ]
